import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { DollarSign, TrendingUp, Calendar, BarChart3, Download } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../../../shared/components/ui/Button';
export function EarningsOverview({ monthlyEarnings, yearlyEarnings, loading }) {
    const [viewType, setViewType] = useState('monthly');
    const currentYear = new Date().getFullYear();
    const currentMonth = new Date().getMonth() + 1;
    const currentYearEarnings = yearlyEarnings?.find(y => y.year === currentYear);
    const currentMonthEarnings = monthlyEarnings?.find(m => m.month === currentMonth && m.year === currentYear);
    const handleExport = () => {
        const data = viewType === 'monthly' ? monthlyEarnings : yearlyEarnings;
        const csvContent = viewType === 'monthly'
            ? "Month,Year,Classes,Total Earnings,Paid,Pending\n" +
                data?.map(item => `${item.month},${item.year},${item.total_classes},${item.total_earnings},${item.paid_earnings},${item.pending_earnings}`).join('\n')
            : "Year,Classes,Total Earnings,Paid,Pending\n" +
                data?.map(item => `${item.year},${item.total_classes},${item.total_earnings},${item.paid_earnings},${item.pending_earnings}`).join('\n');
        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `earnings_${viewType}_${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        window.URL.revokeObjectURL(url);
    };
    if (loading) {
        return (_jsx("div", { className: "bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-gray-200 dark:border-slate-700 p-6", children: _jsxs("div", { className: "animate-pulse", children: [_jsx("div", { className: "h-6 bg-gray-200 dark:bg-slate-600 rounded w-48 mb-4" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [1, 2, 3].map(i => (_jsx("div", { className: "h-24 bg-gray-200 dark:bg-slate-600 rounded" }, i))) })] }) }));
    }
    return (_jsxs("div", { className: "bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-gray-200 dark:border-slate-700 p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: "Earnings Overview" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex bg-gray-100 dark:bg-slate-700 rounded-lg p-1", children: [_jsx("button", { onClick: () => setViewType('monthly'), className: `px-4 py-2 text-sm font-medium rounded-md transition-colors ${viewType === 'monthly'
                                            ? 'bg-white dark:bg-slate-600 text-gray-900 dark:text-white shadow-sm'
                                            : 'text-gray-600 dark:text-slate-400'}`, children: "Monthly" }), _jsx("button", { onClick: () => setViewType('yearly'), className: `px-4 py-2 text-sm font-medium rounded-md transition-colors ${viewType === 'yearly'
                                            ? 'bg-white dark:bg-slate-600 text-gray-900 dark:text-white shadow-sm'
                                            : 'text-gray-600 dark:text-slate-400'}`, children: "Yearly" })] }), _jsxs(Button, { onClick: handleExport, variant: "outline", size: "sm", className: "flex items-center gap-2", children: [_jsx(Download, { className: "w-4 h-4" }), "Export"] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4 mb-8", children: [_jsx("div", { className: "bg-gradient-to-r from-emerald-50 to-emerald-100 dark:from-emerald-900/20 dark:to-emerald-800/20 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("p", { className: "text-sm font-medium text-emerald-700 dark:text-emerald-300", children: ["This ", viewType === 'monthly' ? 'Month' : 'Year'] }), _jsxs("p", { className: "text-2xl font-bold text-emerald-900 dark:text-emerald-100", children: ["\u20B9", viewType === 'monthly'
                                                    ? (currentMonthEarnings?.total_earnings || 0).toLocaleString()
                                                    : (currentYearEarnings?.total_earnings || 0).toLocaleString()] })] }), _jsx(DollarSign, { className: "w-8 h-8 text-emerald-600 dark:text-emerald-400" })] }) }), _jsx("div", { className: "bg-gradient-to-r from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/20 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-blue-700 dark:text-blue-300", children: "Classes Taught" }), _jsx("p", { className: "text-2xl font-bold text-blue-900 dark:text-blue-100", children: viewType === 'monthly'
                                                ? currentMonthEarnings?.total_classes || 0
                                                : currentYearEarnings?.total_classes || 0 })] }), _jsx(Calendar, { className: "w-8 h-8 text-blue-600 dark:text-blue-400" })] }) }), _jsx("div", { className: "bg-gradient-to-r from-purple-50 to-purple-100 dark:from-purple-900/20 dark:to-purple-800/20 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-purple-700 dark:text-purple-300", children: "Paid" }), _jsxs("p", { className: "text-2xl font-bold text-purple-900 dark:text-purple-100", children: ["\u20B9", viewType === 'monthly'
                                                    ? (currentMonthEarnings?.paid_earnings || 0).toLocaleString()
                                                    : (currentYearEarnings?.paid_earnings || 0).toLocaleString()] })] }), _jsx(TrendingUp, { className: "w-8 h-8 text-purple-600 dark:text-purple-400" })] }) }), _jsx("div", { className: "bg-gradient-to-r from-orange-50 to-orange-100 dark:from-orange-900/20 dark:to-orange-800/20 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-orange-700 dark:text-orange-300", children: "Pending" }), _jsxs("p", { className: "text-2xl font-bold text-orange-900 dark:text-orange-100", children: ["\u20B9", viewType === 'monthly'
                                                    ? (currentMonthEarnings?.pending_earnings || 0).toLocaleString()
                                                    : (currentYearEarnings?.pending_earnings || 0).toLocaleString()] })] }), _jsx(BarChart3, { className: "w-8 h-8 text-orange-600 dark:text-orange-400" })] }) })] }), _jsxs("div", { className: "bg-gray-50 dark:bg-slate-700 rounded-lg p-4", children: [_jsxs("h3", { className: "font-semibold text-gray-900 dark:text-white mb-4", children: [viewType === 'monthly' ? 'Monthly' : 'Yearly', " Breakdown"] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-200 dark:border-slate-600", children: [_jsx("th", { className: "text-left py-2 text-gray-600 dark:text-slate-400", children: viewType === 'monthly' ? 'Month' : 'Year' }), _jsx("th", { className: "text-right py-2 text-gray-600 dark:text-slate-400", children: "Classes" }), _jsx("th", { className: "text-right py-2 text-gray-600 dark:text-slate-400", children: "Total" }), _jsx("th", { className: "text-right py-2 text-gray-600 dark:text-slate-400", children: "Paid" }), _jsx("th", { className: "text-right py-2 text-gray-600 dark:text-slate-400", children: "Pending" })] }) }), _jsx("tbody", { children: (viewType === 'monthly' ? monthlyEarnings : yearlyEarnings)?.map((item, index) => (_jsxs("tr", { className: "border-b border-gray-100 dark:border-slate-600 last:border-0", children: [_jsx("td", { className: "py-2 font-medium text-gray-900 dark:text-white", children: viewType === 'monthly'
                                                    ? `${new Date(2024, item.month - 1).toLocaleDateString('en', { month: 'long' })} ${item.year}`
                                                    : item.year }), _jsx("td", { className: "text-right py-2 text-gray-600 dark:text-slate-400", children: item.total_classes }), _jsxs("td", { className: "text-right py-2 font-medium text-gray-900 dark:text-white", children: ["\u20B9", item.total_earnings.toLocaleString()] }), _jsxs("td", { className: "text-right py-2 text-emerald-600 dark:text-emerald-400", children: ["\u20B9", item.paid_earnings.toLocaleString()] }), _jsxs("td", { className: "text-right py-2 text-orange-600 dark:text-orange-400", children: ["\u20B9", item.pending_earnings.toLocaleString()] })] }, index))) })] }) }), (!monthlyEarnings?.length && !yearlyEarnings?.length) && (_jsx("div", { className: "text-center py-8 text-gray-500 dark:text-slate-400", children: "No earnings data available yet." }))] })] }));
}
